version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo "GeoIP URI is $GEOIP_S3_URI"
  build:
    commands:
      - echo "Building monitoring stack images..."

      - docker-compose -f docker-compose.yml build
      - docker push $PROMETHEUS_REPO_URI:latest
      - docker push $LOKI_REPO_URI:latest
      - docker push $ALLOY_REPO_URI:latest

      - mkdir -p deployment
      - cp docker-compose.yml deployment/
      - cp -r scripts deployment/ || mkdir deployment/scripts

artifacts:
  files:
    - appspec.yml
    - deployment/**/*
  name: monitoring-deployment
