FROM grafana/alloy:v1.10.2

RUN apt-get update && \
    apt-get install -y wget && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /etc/alloy /opt/geoip


ARG GEOIP_S3_URI=""

ENV GEOIP_S3_URI ${GEOIP_S3_URI}
RUN wget -O /opt/geoip/geoip.mmdb "${GEOIP_S3_URI}"

RUN ln -sf /opt/geoip/geoip.mmdb /geoip.mmdb

COPY ./config.alloy /etc/alloy/config.alloy
