global:
  scrape_interval: 5s
  scrape_timeout: 3s

scrape_configs:
  - job_name: 'nestjs'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'tms:5440']
  - job_name: 'server'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'node-exporter:9100' ]
  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]
